// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnterSceneRes.proto

#include "EnterSceneRes.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Protocol {
PROTOBUF_CONSTEXPR EnterSceneRes::EnterSceneRes(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.scenename_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.position_)*/nullptr
  , /*decltype(_impl_.result_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct EnterSceneResDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EnterSceneResDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~EnterSceneResDefaultTypeInternal() {}
  union {
    EnterSceneRes _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EnterSceneResDefaultTypeInternal _EnterSceneRes_default_instance_;
}  // namespace Protocol
static ::_pb::Metadata file_level_metadata_EnterSceneRes_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_EnterSceneRes_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_EnterSceneRes_2eproto = nullptr;

const uint32_t TableStruct_EnterSceneRes_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::EnterSceneRes, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::EnterSceneRes, _impl_.result_),
  PROTOBUF_FIELD_OFFSET(::Protocol::EnterSceneRes, _impl_.scenename_),
  PROTOBUF_FIELD_OFFSET(::Protocol::EnterSceneRes, _impl_.position_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Protocol::EnterSceneRes)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Protocol::_EnterSceneRes_default_instance_._instance,
};

const char descriptor_table_protodef_EnterSceneRes_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023EnterSceneRes.proto\022\010Protocol\032\rVector3"
  ".proto\"W\n\rEnterSceneRes\022\016\n\006result\030\001 \001(\005\022"
  "\021\n\tsceneName\030\002 \001(\t\022#\n\010position\030\003 \001(\0132\021.P"
  "rotocol.Vector3b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_EnterSceneRes_2eproto_deps[1] = {
  &::descriptor_table_Vector3_2eproto,
};
static ::_pbi::once_flag descriptor_table_EnterSceneRes_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_EnterSceneRes_2eproto = {
    false, false, 143, descriptor_table_protodef_EnterSceneRes_2eproto,
    "EnterSceneRes.proto",
    &descriptor_table_EnterSceneRes_2eproto_once, descriptor_table_EnterSceneRes_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_EnterSceneRes_2eproto::offsets,
    file_level_metadata_EnterSceneRes_2eproto, file_level_enum_descriptors_EnterSceneRes_2eproto,
    file_level_service_descriptors_EnterSceneRes_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_EnterSceneRes_2eproto_getter() {
  return &descriptor_table_EnterSceneRes_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_EnterSceneRes_2eproto(&descriptor_table_EnterSceneRes_2eproto);
namespace Protocol {

// ===================================================================

class EnterSceneRes::_Internal {
 public:
  static const ::Protocol::Vector3& position(const EnterSceneRes* msg);
};

const ::Protocol::Vector3&
EnterSceneRes::_Internal::position(const EnterSceneRes* msg) {
  return *msg->_impl_.position_;
}
void EnterSceneRes::clear_position() {
  if (GetArenaForAllocation() == nullptr && _impl_.position_ != nullptr) {
    delete _impl_.position_;
  }
  _impl_.position_ = nullptr;
}
EnterSceneRes::EnterSceneRes(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.EnterSceneRes)
}
EnterSceneRes::EnterSceneRes(const EnterSceneRes& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  EnterSceneRes* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.scenename_){}
    , decltype(_impl_.position_){nullptr}
    , decltype(_impl_.result_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.scenename_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.scenename_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_scenename().empty()) {
    _this->_impl_.scenename_.Set(from._internal_scenename(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_position()) {
    _this->_impl_.position_ = new ::Protocol::Vector3(*from._impl_.position_);
  }
  _this->_impl_.result_ = from._impl_.result_;
  // @@protoc_insertion_point(copy_constructor:Protocol.EnterSceneRes)
}

inline void EnterSceneRes::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.scenename_){}
    , decltype(_impl_.position_){nullptr}
    , decltype(_impl_.result_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.scenename_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.scenename_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

EnterSceneRes::~EnterSceneRes() {
  // @@protoc_insertion_point(destructor:Protocol.EnterSceneRes)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void EnterSceneRes::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.scenename_.Destroy();
  if (this != internal_default_instance()) delete _impl_.position_;
}

void EnterSceneRes::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void EnterSceneRes::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.EnterSceneRes)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.scenename_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.position_ != nullptr) {
    delete _impl_.position_;
  }
  _impl_.position_ = nullptr;
  _impl_.result_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* EnterSceneRes::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 result = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.result_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string sceneName = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_scenename();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Protocol.EnterSceneRes.sceneName"));
        } else
          goto handle_unusual;
        continue;
      // .Protocol.Vector3 position = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_position(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* EnterSceneRes::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.EnterSceneRes)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 result = 1;
  if (this->_internal_result() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_result(), target);
  }

  // string sceneName = 2;
  if (!this->_internal_scenename().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_scenename().data(), static_cast<int>(this->_internal_scenename().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Protocol.EnterSceneRes.sceneName");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_scenename(), target);
  }

  // .Protocol.Vector3 position = 3;
  if (this->_internal_has_position()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::position(this),
        _Internal::position(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.EnterSceneRes)
  return target;
}

size_t EnterSceneRes::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.EnterSceneRes)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string sceneName = 2;
  if (!this->_internal_scenename().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_scenename());
  }

  // .Protocol.Vector3 position = 3;
  if (this->_internal_has_position()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.position_);
  }

  // int32 result = 1;
  if (this->_internal_result() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_result());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData EnterSceneRes::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    EnterSceneRes::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*EnterSceneRes::GetClassData() const { return &_class_data_; }


void EnterSceneRes::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<EnterSceneRes*>(&to_msg);
  auto& from = static_cast<const EnterSceneRes&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.EnterSceneRes)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_scenename().empty()) {
    _this->_internal_set_scenename(from._internal_scenename());
  }
  if (from._internal_has_position()) {
    _this->_internal_mutable_position()->::Protocol::Vector3::MergeFrom(
        from._internal_position());
  }
  if (from._internal_result() != 0) {
    _this->_internal_set_result(from._internal_result());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void EnterSceneRes::CopyFrom(const EnterSceneRes& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.EnterSceneRes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EnterSceneRes::IsInitialized() const {
  return true;
}

void EnterSceneRes::InternalSwap(EnterSceneRes* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.scenename_, lhs_arena,
      &other->_impl_.scenename_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(EnterSceneRes, _impl_.result_)
      + sizeof(EnterSceneRes::_impl_.result_)
      - PROTOBUF_FIELD_OFFSET(EnterSceneRes, _impl_.position_)>(
          reinterpret_cast<char*>(&_impl_.position_),
          reinterpret_cast<char*>(&other->_impl_.position_));
}

::PROTOBUF_NAMESPACE_ID::Metadata EnterSceneRes::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_EnterSceneRes_2eproto_getter, &descriptor_table_EnterSceneRes_2eproto_once,
      file_level_metadata_EnterSceneRes_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Protocol::EnterSceneRes*
Arena::CreateMaybeMessage< ::Protocol::EnterSceneRes >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::EnterSceneRes >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
