// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MoveReq.proto

#include "MoveReq.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Protocol {
PROTOBUF_CONSTEXPR MoveReq::MoveReq(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.direction_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MoveReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MoveReqDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MoveReqDefaultTypeInternal() {}
  union {
    MoveReq _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MoveReqDefaultTypeInternal _MoveReq_default_instance_;
}  // namespace Protocol
static ::_pb::Metadata file_level_metadata_MoveReq_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_MoveReq_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_MoveReq_2eproto = nullptr;

const uint32_t TableStruct_MoveReq_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::MoveReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::MoveReq, _impl_.direction_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Protocol::MoveReq)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Protocol::_MoveReq_default_instance_._instance,
};

const char descriptor_table_protodef_MoveReq_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rMoveReq.proto\022\010Protocol\032\rVector3.proto"
  "\"/\n\007MoveReq\022$\n\tdirection\030\001 \001(\0132\021.Protoco"
  "l.Vector3b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_MoveReq_2eproto_deps[1] = {
  &::descriptor_table_Vector3_2eproto,
};
static ::_pbi::once_flag descriptor_table_MoveReq_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_MoveReq_2eproto = {
    false, false, 97, descriptor_table_protodef_MoveReq_2eproto,
    "MoveReq.proto",
    &descriptor_table_MoveReq_2eproto_once, descriptor_table_MoveReq_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_MoveReq_2eproto::offsets,
    file_level_metadata_MoveReq_2eproto, file_level_enum_descriptors_MoveReq_2eproto,
    file_level_service_descriptors_MoveReq_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_MoveReq_2eproto_getter() {
  return &descriptor_table_MoveReq_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_MoveReq_2eproto(&descriptor_table_MoveReq_2eproto);
namespace Protocol {

// ===================================================================

class MoveReq::_Internal {
 public:
  static const ::Protocol::Vector3& direction(const MoveReq* msg);
};

const ::Protocol::Vector3&
MoveReq::_Internal::direction(const MoveReq* msg) {
  return *msg->_impl_.direction_;
}
void MoveReq::clear_direction() {
  if (GetArenaForAllocation() == nullptr && _impl_.direction_ != nullptr) {
    delete _impl_.direction_;
  }
  _impl_.direction_ = nullptr;
}
MoveReq::MoveReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.MoveReq)
}
MoveReq::MoveReq(const MoveReq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MoveReq* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.direction_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_direction()) {
    _this->_impl_.direction_ = new ::Protocol::Vector3(*from._impl_.direction_);
  }
  // @@protoc_insertion_point(copy_constructor:Protocol.MoveReq)
}

inline void MoveReq::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.direction_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

MoveReq::~MoveReq() {
  // @@protoc_insertion_point(destructor:Protocol.MoveReq)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MoveReq::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.direction_;
}

void MoveReq::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MoveReq::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.MoveReq)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.direction_ != nullptr) {
    delete _impl_.direction_;
  }
  _impl_.direction_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MoveReq::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .Protocol.Vector3 direction = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_direction(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* MoveReq::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.MoveReq)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .Protocol.Vector3 direction = 1;
  if (this->_internal_has_direction()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::direction(this),
        _Internal::direction(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.MoveReq)
  return target;
}

size_t MoveReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.MoveReq)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .Protocol.Vector3 direction = 1;
  if (this->_internal_has_direction()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.direction_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MoveReq::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MoveReq::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MoveReq::GetClassData() const { return &_class_data_; }


void MoveReq::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MoveReq*>(&to_msg);
  auto& from = static_cast<const MoveReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.MoveReq)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_direction()) {
    _this->_internal_mutable_direction()->::Protocol::Vector3::MergeFrom(
        from._internal_direction());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MoveReq::CopyFrom(const MoveReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.MoveReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MoveReq::IsInitialized() const {
  return true;
}

void MoveReq::InternalSwap(MoveReq* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.direction_, other->_impl_.direction_);
}

::PROTOBUF_NAMESPACE_ID::Metadata MoveReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_MoveReq_2eproto_getter, &descriptor_table_MoveReq_2eproto_once,
      file_level_metadata_MoveReq_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Protocol::MoveReq*
Arena::CreateMaybeMessage< ::Protocol::MoveReq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::MoveReq >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
