// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NPC_LIST_RES.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_NPC_5fLIST_5fRES_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_NPC_5fLIST_5fRES_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "NPC_INFO.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_NPC_5fLIST_5fRES_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_NPC_5fLIST_5fRES_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_NPC_5fLIST_5fRES_2eproto;
namespace Protocol {
class NPC_LIST_RES;
struct NPC_LIST_RESDefaultTypeInternal;
extern NPC_LIST_RESDefaultTypeInternal _NPC_LIST_RES_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::NPC_LIST_RES* Arena::CreateMaybeMessage<::Protocol::NPC_LIST_RES>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class NPC_LIST_RES final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.NPC_LIST_RES) */ {
 public:
  inline NPC_LIST_RES() : NPC_LIST_RES(nullptr) {}
  ~NPC_LIST_RES() override;
  explicit PROTOBUF_CONSTEXPR NPC_LIST_RES(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  NPC_LIST_RES(const NPC_LIST_RES& from);
  NPC_LIST_RES(NPC_LIST_RES&& from) noexcept
    : NPC_LIST_RES() {
    *this = ::std::move(from);
  }

  inline NPC_LIST_RES& operator=(const NPC_LIST_RES& from) {
    CopyFrom(from);
    return *this;
  }
  inline NPC_LIST_RES& operator=(NPC_LIST_RES&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NPC_LIST_RES& default_instance() {
    return *internal_default_instance();
  }
  static inline const NPC_LIST_RES* internal_default_instance() {
    return reinterpret_cast<const NPC_LIST_RES*>(
               &_NPC_LIST_RES_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(NPC_LIST_RES& a, NPC_LIST_RES& b) {
    a.Swap(&b);
  }
  inline void Swap(NPC_LIST_RES* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NPC_LIST_RES* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NPC_LIST_RES* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<NPC_LIST_RES>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const NPC_LIST_RES& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const NPC_LIST_RES& from) {
    NPC_LIST_RES::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NPC_LIST_RES* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.NPC_LIST_RES";
  }
  protected:
  explicit NPC_LIST_RES(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNPCINFOFieldNumber = 1,
  };
  // repeated .Protocol.NPC_INFO NPC_INFO = 1;
  int npc_info_size() const;
  private:
  int _internal_npc_info_size() const;
  public:
  void clear_npc_info();
  ::Protocol::NPC_INFO* mutable_npc_info(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::NPC_INFO >*
      mutable_npc_info();
  private:
  const ::Protocol::NPC_INFO& _internal_npc_info(int index) const;
  ::Protocol::NPC_INFO* _internal_add_npc_info();
  public:
  const ::Protocol::NPC_INFO& npc_info(int index) const;
  ::Protocol::NPC_INFO* add_npc_info();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::NPC_INFO >&
      npc_info() const;

  // @@protoc_insertion_point(class_scope:Protocol.NPC_LIST_RES)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::NPC_INFO > npc_info_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_NPC_5fLIST_5fRES_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// NPC_LIST_RES

// repeated .Protocol.NPC_INFO NPC_INFO = 1;
inline int NPC_LIST_RES::_internal_npc_info_size() const {
  return _impl_.npc_info_.size();
}
inline int NPC_LIST_RES::npc_info_size() const {
  return _internal_npc_info_size();
}
inline ::Protocol::NPC_INFO* NPC_LIST_RES::mutable_npc_info(int index) {
  // @@protoc_insertion_point(field_mutable:Protocol.NPC_LIST_RES.NPC_INFO)
  return _impl_.npc_info_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::NPC_INFO >*
NPC_LIST_RES::mutable_npc_info() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.NPC_LIST_RES.NPC_INFO)
  return &_impl_.npc_info_;
}
inline const ::Protocol::NPC_INFO& NPC_LIST_RES::_internal_npc_info(int index) const {
  return _impl_.npc_info_.Get(index);
}
inline const ::Protocol::NPC_INFO& NPC_LIST_RES::npc_info(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.NPC_LIST_RES.NPC_INFO)
  return _internal_npc_info(index);
}
inline ::Protocol::NPC_INFO* NPC_LIST_RES::_internal_add_npc_info() {
  return _impl_.npc_info_.Add();
}
inline ::Protocol::NPC_INFO* NPC_LIST_RES::add_npc_info() {
  ::Protocol::NPC_INFO* _add = _internal_add_npc_info();
  // @@protoc_insertion_point(field_add:Protocol.NPC_LIST_RES.NPC_INFO)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::NPC_INFO >&
NPC_LIST_RES::npc_info() const {
  // @@protoc_insertion_point(field_list:Protocol.NPC_LIST_RES.NPC_INFO)
  return _impl_.npc_info_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_NPC_5fLIST_5fRES_2eproto
