// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NPCInfo.proto

#include "NPCInfo.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Protocol {
PROTOBUF_CONSTEXPR NPCInfo::NPCInfo(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.npcbaseinfo_)*/nullptr
  , /*decltype(_impl_.statinfo_)*/nullptr
  , /*decltype(_impl_.position_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct NPCInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NPCInfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~NPCInfoDefaultTypeInternal() {}
  union {
    NPCInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NPCInfoDefaultTypeInternal _NPCInfo_default_instance_;
}  // namespace Protocol
static ::_pb::Metadata file_level_metadata_NPCInfo_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_NPCInfo_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_NPCInfo_2eproto = nullptr;

const uint32_t TableStruct_NPCInfo_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::NPCInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::NPCInfo, _impl_.npcbaseinfo_),
  PROTOBUF_FIELD_OFFSET(::Protocol::NPCInfo, _impl_.statinfo_),
  PROTOBUF_FIELD_OFFSET(::Protocol::NPCInfo, _impl_.position_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Protocol::NPCInfo)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Protocol::_NPCInfo_default_instance_._instance,
};

const char descriptor_table_protodef_NPCInfo_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rNPCInfo.proto\022\010Protocol\032\rVector3.proto"
  "\032\016StatInfo.proto\032\021NPCBaseInfo.proto\"\200\001\n\007"
  "NPCInfo\022*\n\013npcBaseInfo\030\001 \001(\0132\025.Protocol."
  "NPCBaseInfo\022$\n\010statInfo\030\002 \001(\0132\022.Protocol"
  ".StatInfo\022#\n\010position\030\003 \001(\0132\021.Protocol.V"
  "ector3b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_NPCInfo_2eproto_deps[3] = {
  &::descriptor_table_NPCBaseInfo_2eproto,
  &::descriptor_table_StatInfo_2eproto,
  &::descriptor_table_Vector3_2eproto,
};
static ::_pbi::once_flag descriptor_table_NPCInfo_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_NPCInfo_2eproto = {
    false, false, 214, descriptor_table_protodef_NPCInfo_2eproto,
    "NPCInfo.proto",
    &descriptor_table_NPCInfo_2eproto_once, descriptor_table_NPCInfo_2eproto_deps, 3, 1,
    schemas, file_default_instances, TableStruct_NPCInfo_2eproto::offsets,
    file_level_metadata_NPCInfo_2eproto, file_level_enum_descriptors_NPCInfo_2eproto,
    file_level_service_descriptors_NPCInfo_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_NPCInfo_2eproto_getter() {
  return &descriptor_table_NPCInfo_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_NPCInfo_2eproto(&descriptor_table_NPCInfo_2eproto);
namespace Protocol {

// ===================================================================

class NPCInfo::_Internal {
 public:
  static const ::Protocol::NPCBaseInfo& npcbaseinfo(const NPCInfo* msg);
  static const ::Protocol::StatInfo& statinfo(const NPCInfo* msg);
  static const ::Protocol::Vector3& position(const NPCInfo* msg);
};

const ::Protocol::NPCBaseInfo&
NPCInfo::_Internal::npcbaseinfo(const NPCInfo* msg) {
  return *msg->_impl_.npcbaseinfo_;
}
const ::Protocol::StatInfo&
NPCInfo::_Internal::statinfo(const NPCInfo* msg) {
  return *msg->_impl_.statinfo_;
}
const ::Protocol::Vector3&
NPCInfo::_Internal::position(const NPCInfo* msg) {
  return *msg->_impl_.position_;
}
void NPCInfo::clear_npcbaseinfo() {
  if (GetArenaForAllocation() == nullptr && _impl_.npcbaseinfo_ != nullptr) {
    delete _impl_.npcbaseinfo_;
  }
  _impl_.npcbaseinfo_ = nullptr;
}
void NPCInfo::clear_statinfo() {
  if (GetArenaForAllocation() == nullptr && _impl_.statinfo_ != nullptr) {
    delete _impl_.statinfo_;
  }
  _impl_.statinfo_ = nullptr;
}
void NPCInfo::clear_position() {
  if (GetArenaForAllocation() == nullptr && _impl_.position_ != nullptr) {
    delete _impl_.position_;
  }
  _impl_.position_ = nullptr;
}
NPCInfo::NPCInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.NPCInfo)
}
NPCInfo::NPCInfo(const NPCInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  NPCInfo* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.npcbaseinfo_){nullptr}
    , decltype(_impl_.statinfo_){nullptr}
    , decltype(_impl_.position_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_npcbaseinfo()) {
    _this->_impl_.npcbaseinfo_ = new ::Protocol::NPCBaseInfo(*from._impl_.npcbaseinfo_);
  }
  if (from._internal_has_statinfo()) {
    _this->_impl_.statinfo_ = new ::Protocol::StatInfo(*from._impl_.statinfo_);
  }
  if (from._internal_has_position()) {
    _this->_impl_.position_ = new ::Protocol::Vector3(*from._impl_.position_);
  }
  // @@protoc_insertion_point(copy_constructor:Protocol.NPCInfo)
}

inline void NPCInfo::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.npcbaseinfo_){nullptr}
    , decltype(_impl_.statinfo_){nullptr}
    , decltype(_impl_.position_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

NPCInfo::~NPCInfo() {
  // @@protoc_insertion_point(destructor:Protocol.NPCInfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void NPCInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.npcbaseinfo_;
  if (this != internal_default_instance()) delete _impl_.statinfo_;
  if (this != internal_default_instance()) delete _impl_.position_;
}

void NPCInfo::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void NPCInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.NPCInfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.npcbaseinfo_ != nullptr) {
    delete _impl_.npcbaseinfo_;
  }
  _impl_.npcbaseinfo_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.statinfo_ != nullptr) {
    delete _impl_.statinfo_;
  }
  _impl_.statinfo_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.position_ != nullptr) {
    delete _impl_.position_;
  }
  _impl_.position_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* NPCInfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .Protocol.NPCBaseInfo npcBaseInfo = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_npcbaseinfo(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Protocol.StatInfo statInfo = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_statinfo(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Protocol.Vector3 position = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_position(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* NPCInfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.NPCInfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .Protocol.NPCBaseInfo npcBaseInfo = 1;
  if (this->_internal_has_npcbaseinfo()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::npcbaseinfo(this),
        _Internal::npcbaseinfo(this).GetCachedSize(), target, stream);
  }

  // .Protocol.StatInfo statInfo = 2;
  if (this->_internal_has_statinfo()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::statinfo(this),
        _Internal::statinfo(this).GetCachedSize(), target, stream);
  }

  // .Protocol.Vector3 position = 3;
  if (this->_internal_has_position()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::position(this),
        _Internal::position(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.NPCInfo)
  return target;
}

size_t NPCInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.NPCInfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .Protocol.NPCBaseInfo npcBaseInfo = 1;
  if (this->_internal_has_npcbaseinfo()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.npcbaseinfo_);
  }

  // .Protocol.StatInfo statInfo = 2;
  if (this->_internal_has_statinfo()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.statinfo_);
  }

  // .Protocol.Vector3 position = 3;
  if (this->_internal_has_position()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.position_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData NPCInfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    NPCInfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*NPCInfo::GetClassData() const { return &_class_data_; }


void NPCInfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<NPCInfo*>(&to_msg);
  auto& from = static_cast<const NPCInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.NPCInfo)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_npcbaseinfo()) {
    _this->_internal_mutable_npcbaseinfo()->::Protocol::NPCBaseInfo::MergeFrom(
        from._internal_npcbaseinfo());
  }
  if (from._internal_has_statinfo()) {
    _this->_internal_mutable_statinfo()->::Protocol::StatInfo::MergeFrom(
        from._internal_statinfo());
  }
  if (from._internal_has_position()) {
    _this->_internal_mutable_position()->::Protocol::Vector3::MergeFrom(
        from._internal_position());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void NPCInfo::CopyFrom(const NPCInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.NPCInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NPCInfo::IsInitialized() const {
  return true;
}

void NPCInfo::InternalSwap(NPCInfo* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(NPCInfo, _impl_.position_)
      + sizeof(NPCInfo::_impl_.position_)
      - PROTOBUF_FIELD_OFFSET(NPCInfo, _impl_.npcbaseinfo_)>(
          reinterpret_cast<char*>(&_impl_.npcbaseinfo_),
          reinterpret_cast<char*>(&other->_impl_.npcbaseinfo_));
}

::PROTOBUF_NAMESPACE_ID::Metadata NPCInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_NPCInfo_2eproto_getter, &descriptor_table_NPCInfo_2eproto_once,
      file_level_metadata_NPCInfo_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Protocol::NPCInfo*
Arena::CreateMaybeMessage< ::Protocol::NPCInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::NPCInfo >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
