// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NPCSpawned.proto

#include "NPCSpawned.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Protocol {
PROTOBUF_CONSTEXPR NPCSpawned::NPCSpawned(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.npcinfo_)*/nullptr
  , /*decltype(_impl_.statinfo_)*/nullptr
  , /*decltype(_impl_.position_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct NPCSpawnedDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NPCSpawnedDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~NPCSpawnedDefaultTypeInternal() {}
  union {
    NPCSpawned _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NPCSpawnedDefaultTypeInternal _NPCSpawned_default_instance_;
}  // namespace Protocol
static ::_pb::Metadata file_level_metadata_NPCSpawned_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_NPCSpawned_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_NPCSpawned_2eproto = nullptr;

const uint32_t TableStruct_NPCSpawned_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::NPCSpawned, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::NPCSpawned, _impl_.npcinfo_),
  PROTOBUF_FIELD_OFFSET(::Protocol::NPCSpawned, _impl_.statinfo_),
  PROTOBUF_FIELD_OFFSET(::Protocol::NPCSpawned, _impl_.position_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Protocol::NPCSpawned)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Protocol::_NPCSpawned_default_instance_._instance,
};

const char descriptor_table_protodef_NPCSpawned_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020NPCSpawned.proto\022\010Protocol\032\rVector3.pr"
  "oto\032\016StatInfo.proto\032\rNPCInfo.proto\"{\n\nNP"
  "CSpawned\022\"\n\007npcInfo\030\001 \001(\0132\021.Protocol.NPC"
  "Info\022$\n\010statInfo\030\002 \001(\0132\022.Protocol.StatIn"
  "fo\022#\n\010position\030\003 \001(\0132\021.Protocol.Vector3b"
  "\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_NPCSpawned_2eproto_deps[3] = {
  &::descriptor_table_NPCInfo_2eproto,
  &::descriptor_table_StatInfo_2eproto,
  &::descriptor_table_Vector3_2eproto,
};
static ::_pbi::once_flag descriptor_table_NPCSpawned_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_NPCSpawned_2eproto = {
    false, false, 207, descriptor_table_protodef_NPCSpawned_2eproto,
    "NPCSpawned.proto",
    &descriptor_table_NPCSpawned_2eproto_once, descriptor_table_NPCSpawned_2eproto_deps, 3, 1,
    schemas, file_default_instances, TableStruct_NPCSpawned_2eproto::offsets,
    file_level_metadata_NPCSpawned_2eproto, file_level_enum_descriptors_NPCSpawned_2eproto,
    file_level_service_descriptors_NPCSpawned_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_NPCSpawned_2eproto_getter() {
  return &descriptor_table_NPCSpawned_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_NPCSpawned_2eproto(&descriptor_table_NPCSpawned_2eproto);
namespace Protocol {

// ===================================================================

class NPCSpawned::_Internal {
 public:
  static const ::Protocol::NPCInfo& npcinfo(const NPCSpawned* msg);
  static const ::Protocol::StatInfo& statinfo(const NPCSpawned* msg);
  static const ::Protocol::Vector3& position(const NPCSpawned* msg);
};

const ::Protocol::NPCInfo&
NPCSpawned::_Internal::npcinfo(const NPCSpawned* msg) {
  return *msg->_impl_.npcinfo_;
}
const ::Protocol::StatInfo&
NPCSpawned::_Internal::statinfo(const NPCSpawned* msg) {
  return *msg->_impl_.statinfo_;
}
const ::Protocol::Vector3&
NPCSpawned::_Internal::position(const NPCSpawned* msg) {
  return *msg->_impl_.position_;
}
void NPCSpawned::clear_npcinfo() {
  if (GetArenaForAllocation() == nullptr && _impl_.npcinfo_ != nullptr) {
    delete _impl_.npcinfo_;
  }
  _impl_.npcinfo_ = nullptr;
}
void NPCSpawned::clear_statinfo() {
  if (GetArenaForAllocation() == nullptr && _impl_.statinfo_ != nullptr) {
    delete _impl_.statinfo_;
  }
  _impl_.statinfo_ = nullptr;
}
void NPCSpawned::clear_position() {
  if (GetArenaForAllocation() == nullptr && _impl_.position_ != nullptr) {
    delete _impl_.position_;
  }
  _impl_.position_ = nullptr;
}
NPCSpawned::NPCSpawned(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.NPCSpawned)
}
NPCSpawned::NPCSpawned(const NPCSpawned& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  NPCSpawned* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.npcinfo_){nullptr}
    , decltype(_impl_.statinfo_){nullptr}
    , decltype(_impl_.position_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_npcinfo()) {
    _this->_impl_.npcinfo_ = new ::Protocol::NPCInfo(*from._impl_.npcinfo_);
  }
  if (from._internal_has_statinfo()) {
    _this->_impl_.statinfo_ = new ::Protocol::StatInfo(*from._impl_.statinfo_);
  }
  if (from._internal_has_position()) {
    _this->_impl_.position_ = new ::Protocol::Vector3(*from._impl_.position_);
  }
  // @@protoc_insertion_point(copy_constructor:Protocol.NPCSpawned)
}

inline void NPCSpawned::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.npcinfo_){nullptr}
    , decltype(_impl_.statinfo_){nullptr}
    , decltype(_impl_.position_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

NPCSpawned::~NPCSpawned() {
  // @@protoc_insertion_point(destructor:Protocol.NPCSpawned)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void NPCSpawned::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.npcinfo_;
  if (this != internal_default_instance()) delete _impl_.statinfo_;
  if (this != internal_default_instance()) delete _impl_.position_;
}

void NPCSpawned::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void NPCSpawned::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.NPCSpawned)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.npcinfo_ != nullptr) {
    delete _impl_.npcinfo_;
  }
  _impl_.npcinfo_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.statinfo_ != nullptr) {
    delete _impl_.statinfo_;
  }
  _impl_.statinfo_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.position_ != nullptr) {
    delete _impl_.position_;
  }
  _impl_.position_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* NPCSpawned::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .Protocol.NPCInfo npcInfo = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_npcinfo(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Protocol.StatInfo statInfo = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_statinfo(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Protocol.Vector3 position = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_position(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* NPCSpawned::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.NPCSpawned)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .Protocol.NPCInfo npcInfo = 1;
  if (this->_internal_has_npcinfo()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::npcinfo(this),
        _Internal::npcinfo(this).GetCachedSize(), target, stream);
  }

  // .Protocol.StatInfo statInfo = 2;
  if (this->_internal_has_statinfo()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::statinfo(this),
        _Internal::statinfo(this).GetCachedSize(), target, stream);
  }

  // .Protocol.Vector3 position = 3;
  if (this->_internal_has_position()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::position(this),
        _Internal::position(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.NPCSpawned)
  return target;
}

size_t NPCSpawned::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.NPCSpawned)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .Protocol.NPCInfo npcInfo = 1;
  if (this->_internal_has_npcinfo()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.npcinfo_);
  }

  // .Protocol.StatInfo statInfo = 2;
  if (this->_internal_has_statinfo()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.statinfo_);
  }

  // .Protocol.Vector3 position = 3;
  if (this->_internal_has_position()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.position_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData NPCSpawned::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    NPCSpawned::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*NPCSpawned::GetClassData() const { return &_class_data_; }


void NPCSpawned::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<NPCSpawned*>(&to_msg);
  auto& from = static_cast<const NPCSpawned&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.NPCSpawned)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_npcinfo()) {
    _this->_internal_mutable_npcinfo()->::Protocol::NPCInfo::MergeFrom(
        from._internal_npcinfo());
  }
  if (from._internal_has_statinfo()) {
    _this->_internal_mutable_statinfo()->::Protocol::StatInfo::MergeFrom(
        from._internal_statinfo());
  }
  if (from._internal_has_position()) {
    _this->_internal_mutable_position()->::Protocol::Vector3::MergeFrom(
        from._internal_position());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void NPCSpawned::CopyFrom(const NPCSpawned& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.NPCSpawned)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NPCSpawned::IsInitialized() const {
  return true;
}

void NPCSpawned::InternalSwap(NPCSpawned* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(NPCSpawned, _impl_.position_)
      + sizeof(NPCSpawned::_impl_.position_)
      - PROTOBUF_FIELD_OFFSET(NPCSpawned, _impl_.npcinfo_)>(
          reinterpret_cast<char*>(&_impl_.npcinfo_),
          reinterpret_cast<char*>(&other->_impl_.npcinfo_));
}

::PROTOBUF_NAMESPACE_ID::Metadata NPCSpawned::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_NPCSpawned_2eproto_getter, &descriptor_table_NPCSpawned_2eproto_once,
      file_level_metadata_NPCSpawned_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Protocol::NPCSpawned*
Arena::CreateMaybeMessage< ::Protocol::NPCSpawned >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::NPCSpawned >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
