// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POSITION_UPDATE.proto

#include "POSITION_UPDATE.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Protocol {
PROTOBUF_CONSTEXPR POSITION_UPDATE::POSITION_UPDATE(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.position_)*/nullptr
  , /*decltype(_impl_.movedirection_)*/nullptr
  , /*decltype(_impl_.transformentitytype_)*/0
  , /*decltype(_impl_.transformentityid_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct POSITION_UPDATEDefaultTypeInternal {
  PROTOBUF_CONSTEXPR POSITION_UPDATEDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~POSITION_UPDATEDefaultTypeInternal() {}
  union {
    POSITION_UPDATE _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 POSITION_UPDATEDefaultTypeInternal _POSITION_UPDATE_default_instance_;
}  // namespace Protocol
static ::_pb::Metadata file_level_metadata_POSITION_5fUPDATE_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_POSITION_5fUPDATE_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_POSITION_5fUPDATE_2eproto = nullptr;

const uint32_t TableStruct_POSITION_5fUPDATE_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::POSITION_UPDATE, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::POSITION_UPDATE, _impl_.transformentitytype_),
  PROTOBUF_FIELD_OFFSET(::Protocol::POSITION_UPDATE, _impl_.transformentityid_),
  PROTOBUF_FIELD_OFFSET(::Protocol::POSITION_UPDATE, _impl_.position_),
  PROTOBUF_FIELD_OFFSET(::Protocol::POSITION_UPDATE, _impl_.movedirection_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Protocol::POSITION_UPDATE)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Protocol::_POSITION_UPDATE_default_instance_._instance,
};

const char descriptor_table_protodef_POSITION_5fUPDATE_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\025POSITION_UPDATE.proto\022\010Protocol\032\rVECTO"
  "R3.proto\"\230\001\n\017POSITION_UPDATE\022\033\n\023transfor"
  "mEntityType\030\001 \001(\005\022\031\n\021transformEntityId\030\002"
  " \001(\005\022#\n\010position\030\003 \001(\0132\021.Protocol.VECTOR"
  "3\022(\n\rmoveDirection\030\004 \001(\0132\021.Protocol.VECT"
  "OR3b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_POSITION_5fUPDATE_2eproto_deps[1] = {
  &::descriptor_table_VECTOR3_2eproto,
};
static ::_pbi::once_flag descriptor_table_POSITION_5fUPDATE_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_POSITION_5fUPDATE_2eproto = {
    false, false, 211, descriptor_table_protodef_POSITION_5fUPDATE_2eproto,
    "POSITION_UPDATE.proto",
    &descriptor_table_POSITION_5fUPDATE_2eproto_once, descriptor_table_POSITION_5fUPDATE_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_POSITION_5fUPDATE_2eproto::offsets,
    file_level_metadata_POSITION_5fUPDATE_2eproto, file_level_enum_descriptors_POSITION_5fUPDATE_2eproto,
    file_level_service_descriptors_POSITION_5fUPDATE_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_POSITION_5fUPDATE_2eproto_getter() {
  return &descriptor_table_POSITION_5fUPDATE_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_POSITION_5fUPDATE_2eproto(&descriptor_table_POSITION_5fUPDATE_2eproto);
namespace Protocol {

// ===================================================================

class POSITION_UPDATE::_Internal {
 public:
  static const ::Protocol::VECTOR3& position(const POSITION_UPDATE* msg);
  static const ::Protocol::VECTOR3& movedirection(const POSITION_UPDATE* msg);
};

const ::Protocol::VECTOR3&
POSITION_UPDATE::_Internal::position(const POSITION_UPDATE* msg) {
  return *msg->_impl_.position_;
}
const ::Protocol::VECTOR3&
POSITION_UPDATE::_Internal::movedirection(const POSITION_UPDATE* msg) {
  return *msg->_impl_.movedirection_;
}
void POSITION_UPDATE::clear_position() {
  if (GetArenaForAllocation() == nullptr && _impl_.position_ != nullptr) {
    delete _impl_.position_;
  }
  _impl_.position_ = nullptr;
}
void POSITION_UPDATE::clear_movedirection() {
  if (GetArenaForAllocation() == nullptr && _impl_.movedirection_ != nullptr) {
    delete _impl_.movedirection_;
  }
  _impl_.movedirection_ = nullptr;
}
POSITION_UPDATE::POSITION_UPDATE(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.POSITION_UPDATE)
}
POSITION_UPDATE::POSITION_UPDATE(const POSITION_UPDATE& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  POSITION_UPDATE* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.position_){nullptr}
    , decltype(_impl_.movedirection_){nullptr}
    , decltype(_impl_.transformentitytype_){}
    , decltype(_impl_.transformentityid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_position()) {
    _this->_impl_.position_ = new ::Protocol::VECTOR3(*from._impl_.position_);
  }
  if (from._internal_has_movedirection()) {
    _this->_impl_.movedirection_ = new ::Protocol::VECTOR3(*from._impl_.movedirection_);
  }
  ::memcpy(&_impl_.transformentitytype_, &from._impl_.transformentitytype_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.transformentityid_) -
    reinterpret_cast<char*>(&_impl_.transformentitytype_)) + sizeof(_impl_.transformentityid_));
  // @@protoc_insertion_point(copy_constructor:Protocol.POSITION_UPDATE)
}

inline void POSITION_UPDATE::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.position_){nullptr}
    , decltype(_impl_.movedirection_){nullptr}
    , decltype(_impl_.transformentitytype_){0}
    , decltype(_impl_.transformentityid_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

POSITION_UPDATE::~POSITION_UPDATE() {
  // @@protoc_insertion_point(destructor:Protocol.POSITION_UPDATE)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void POSITION_UPDATE::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.position_;
  if (this != internal_default_instance()) delete _impl_.movedirection_;
}

void POSITION_UPDATE::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void POSITION_UPDATE::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.POSITION_UPDATE)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.position_ != nullptr) {
    delete _impl_.position_;
  }
  _impl_.position_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.movedirection_ != nullptr) {
    delete _impl_.movedirection_;
  }
  _impl_.movedirection_ = nullptr;
  ::memset(&_impl_.transformentitytype_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.transformentityid_) -
      reinterpret_cast<char*>(&_impl_.transformentitytype_)) + sizeof(_impl_.transformentityid_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* POSITION_UPDATE::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 transformEntityType = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.transformentitytype_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 transformEntityId = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.transformentityid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Protocol.VECTOR3 position = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_position(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Protocol.VECTOR3 moveDirection = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_movedirection(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* POSITION_UPDATE::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.POSITION_UPDATE)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 transformEntityType = 1;
  if (this->_internal_transformentitytype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_transformentitytype(), target);
  }

  // int32 transformEntityId = 2;
  if (this->_internal_transformentityid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_transformentityid(), target);
  }

  // .Protocol.VECTOR3 position = 3;
  if (this->_internal_has_position()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::position(this),
        _Internal::position(this).GetCachedSize(), target, stream);
  }

  // .Protocol.VECTOR3 moveDirection = 4;
  if (this->_internal_has_movedirection()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::movedirection(this),
        _Internal::movedirection(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.POSITION_UPDATE)
  return target;
}

size_t POSITION_UPDATE::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.POSITION_UPDATE)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .Protocol.VECTOR3 position = 3;
  if (this->_internal_has_position()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.position_);
  }

  // .Protocol.VECTOR3 moveDirection = 4;
  if (this->_internal_has_movedirection()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.movedirection_);
  }

  // int32 transformEntityType = 1;
  if (this->_internal_transformentitytype() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_transformentitytype());
  }

  // int32 transformEntityId = 2;
  if (this->_internal_transformentityid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_transformentityid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData POSITION_UPDATE::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    POSITION_UPDATE::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*POSITION_UPDATE::GetClassData() const { return &_class_data_; }


void POSITION_UPDATE::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<POSITION_UPDATE*>(&to_msg);
  auto& from = static_cast<const POSITION_UPDATE&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.POSITION_UPDATE)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_position()) {
    _this->_internal_mutable_position()->::Protocol::VECTOR3::MergeFrom(
        from._internal_position());
  }
  if (from._internal_has_movedirection()) {
    _this->_internal_mutable_movedirection()->::Protocol::VECTOR3::MergeFrom(
        from._internal_movedirection());
  }
  if (from._internal_transformentitytype() != 0) {
    _this->_internal_set_transformentitytype(from._internal_transformentitytype());
  }
  if (from._internal_transformentityid() != 0) {
    _this->_internal_set_transformentityid(from._internal_transformentityid());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void POSITION_UPDATE::CopyFrom(const POSITION_UPDATE& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.POSITION_UPDATE)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool POSITION_UPDATE::IsInitialized() const {
  return true;
}

void POSITION_UPDATE::InternalSwap(POSITION_UPDATE* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(POSITION_UPDATE, _impl_.transformentityid_)
      + sizeof(POSITION_UPDATE::_impl_.transformentityid_)
      - PROTOBUF_FIELD_OFFSET(POSITION_UPDATE, _impl_.position_)>(
          reinterpret_cast<char*>(&_impl_.position_),
          reinterpret_cast<char*>(&other->_impl_.position_));
}

::PROTOBUF_NAMESPACE_ID::Metadata POSITION_UPDATE::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_POSITION_5fUPDATE_2eproto_getter, &descriptor_table_POSITION_5fUPDATE_2eproto_once,
      file_level_metadata_POSITION_5fUPDATE_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Protocol::POSITION_UPDATE*
Arena::CreateMaybeMessage< ::Protocol::POSITION_UPDATE >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::POSITION_UPDATE >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
