// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PROJECTILE_SPAWNED_LIST.proto

#include "PROJECTILE_SPAWNED_LIST.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Protocol {
PROTOBUF_CONSTEXPR PROJECTILE_SPAWNED_LIST::PROJECTILE_SPAWNED_LIST(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.projectileinfo_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PROJECTILE_SPAWNED_LISTDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PROJECTILE_SPAWNED_LISTDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PROJECTILE_SPAWNED_LISTDefaultTypeInternal() {}
  union {
    PROJECTILE_SPAWNED_LIST _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROJECTILE_SPAWNED_LISTDefaultTypeInternal _PROJECTILE_SPAWNED_LIST_default_instance_;
}  // namespace Protocol
static ::_pb::Metadata file_level_metadata_PROJECTILE_5fSPAWNED_5fLIST_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_PROJECTILE_5fSPAWNED_5fLIST_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_PROJECTILE_5fSPAWNED_5fLIST_2eproto = nullptr;

const uint32_t TableStruct_PROJECTILE_5fSPAWNED_5fLIST_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::PROJECTILE_SPAWNED_LIST, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::PROJECTILE_SPAWNED_LIST, _impl_.projectileinfo_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Protocol::PROJECTILE_SPAWNED_LIST)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Protocol::_PROJECTILE_SPAWNED_LIST_default_instance_._instance,
};

const char descriptor_table_protodef_PROJECTILE_5fSPAWNED_5fLIST_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\035PROJECTILE_SPAWNED_LIST.proto\022\010Protoco"
  "l\032\025PROJECTILE_INFO.proto\"L\n\027PROJECTILE_S"
  "PAWNED_LIST\0221\n\016projectileInfo\030\001 \003(\0132\031.Pr"
  "otocol.PROJECTILE_INFOb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_PROJECTILE_5fSPAWNED_5fLIST_2eproto_deps[1] = {
  &::descriptor_table_PROJECTILE_5fINFO_2eproto,
};
static ::_pbi::once_flag descriptor_table_PROJECTILE_5fSPAWNED_5fLIST_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_PROJECTILE_5fSPAWNED_5fLIST_2eproto = {
    false, false, 150, descriptor_table_protodef_PROJECTILE_5fSPAWNED_5fLIST_2eproto,
    "PROJECTILE_SPAWNED_LIST.proto",
    &descriptor_table_PROJECTILE_5fSPAWNED_5fLIST_2eproto_once, descriptor_table_PROJECTILE_5fSPAWNED_5fLIST_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_PROJECTILE_5fSPAWNED_5fLIST_2eproto::offsets,
    file_level_metadata_PROJECTILE_5fSPAWNED_5fLIST_2eproto, file_level_enum_descriptors_PROJECTILE_5fSPAWNED_5fLIST_2eproto,
    file_level_service_descriptors_PROJECTILE_5fSPAWNED_5fLIST_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_PROJECTILE_5fSPAWNED_5fLIST_2eproto_getter() {
  return &descriptor_table_PROJECTILE_5fSPAWNED_5fLIST_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_PROJECTILE_5fSPAWNED_5fLIST_2eproto(&descriptor_table_PROJECTILE_5fSPAWNED_5fLIST_2eproto);
namespace Protocol {

// ===================================================================

class PROJECTILE_SPAWNED_LIST::_Internal {
 public:
};

void PROJECTILE_SPAWNED_LIST::clear_projectileinfo() {
  _impl_.projectileinfo_.Clear();
}
PROJECTILE_SPAWNED_LIST::PROJECTILE_SPAWNED_LIST(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.PROJECTILE_SPAWNED_LIST)
}
PROJECTILE_SPAWNED_LIST::PROJECTILE_SPAWNED_LIST(const PROJECTILE_SPAWNED_LIST& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PROJECTILE_SPAWNED_LIST* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.projectileinfo_){from._impl_.projectileinfo_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Protocol.PROJECTILE_SPAWNED_LIST)
}

inline void PROJECTILE_SPAWNED_LIST::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.projectileinfo_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PROJECTILE_SPAWNED_LIST::~PROJECTILE_SPAWNED_LIST() {
  // @@protoc_insertion_point(destructor:Protocol.PROJECTILE_SPAWNED_LIST)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PROJECTILE_SPAWNED_LIST::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.projectileinfo_.~RepeatedPtrField();
}

void PROJECTILE_SPAWNED_LIST::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PROJECTILE_SPAWNED_LIST::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.PROJECTILE_SPAWNED_LIST)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.projectileinfo_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PROJECTILE_SPAWNED_LIST::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .Protocol.PROJECTILE_INFO projectileInfo = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_projectileinfo(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PROJECTILE_SPAWNED_LIST::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.PROJECTILE_SPAWNED_LIST)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .Protocol.PROJECTILE_INFO projectileInfo = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_projectileinfo_size()); i < n; i++) {
    const auto& repfield = this->_internal_projectileinfo(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.PROJECTILE_SPAWNED_LIST)
  return target;
}

size_t PROJECTILE_SPAWNED_LIST::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.PROJECTILE_SPAWNED_LIST)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .Protocol.PROJECTILE_INFO projectileInfo = 1;
  total_size += 1UL * this->_internal_projectileinfo_size();
  for (const auto& msg : this->_impl_.projectileinfo_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PROJECTILE_SPAWNED_LIST::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PROJECTILE_SPAWNED_LIST::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PROJECTILE_SPAWNED_LIST::GetClassData() const { return &_class_data_; }


void PROJECTILE_SPAWNED_LIST::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PROJECTILE_SPAWNED_LIST*>(&to_msg);
  auto& from = static_cast<const PROJECTILE_SPAWNED_LIST&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.PROJECTILE_SPAWNED_LIST)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.projectileinfo_.MergeFrom(from._impl_.projectileinfo_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PROJECTILE_SPAWNED_LIST::CopyFrom(const PROJECTILE_SPAWNED_LIST& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.PROJECTILE_SPAWNED_LIST)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PROJECTILE_SPAWNED_LIST::IsInitialized() const {
  return true;
}

void PROJECTILE_SPAWNED_LIST::InternalSwap(PROJECTILE_SPAWNED_LIST* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.projectileinfo_.InternalSwap(&other->_impl_.projectileinfo_);
}

::PROTOBUF_NAMESPACE_ID::Metadata PROJECTILE_SPAWNED_LIST::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_PROJECTILE_5fSPAWNED_5fLIST_2eproto_getter, &descriptor_table_PROJECTILE_5fSPAWNED_5fLIST_2eproto_once,
      file_level_metadata_PROJECTILE_5fSPAWNED_5fLIST_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Protocol::PROJECTILE_SPAWNED_LIST*
Arena::CreateMaybeMessage< ::Protocol::PROJECTILE_SPAWNED_LIST >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::PROJECTILE_SPAWNED_LIST >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
