// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: USE_SKILL_REQ.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_USE_5fSKILL_5fREQ_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_USE_5fSKILL_5fREQ_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "VECTOR3.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_USE_5fSKILL_5fREQ_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_USE_5fSKILL_5fREQ_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_USE_5fSKILL_5fREQ_2eproto;
namespace Protocol {
class USE_SKILL_REQ;
struct USE_SKILL_REQDefaultTypeInternal;
extern USE_SKILL_REQDefaultTypeInternal _USE_SKILL_REQ_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::USE_SKILL_REQ* Arena::CreateMaybeMessage<::Protocol::USE_SKILL_REQ>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class USE_SKILL_REQ final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.USE_SKILL_REQ) */ {
 public:
  inline USE_SKILL_REQ() : USE_SKILL_REQ(nullptr) {}
  ~USE_SKILL_REQ() override;
  explicit PROTOBUF_CONSTEXPR USE_SKILL_REQ(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  USE_SKILL_REQ(const USE_SKILL_REQ& from);
  USE_SKILL_REQ(USE_SKILL_REQ&& from) noexcept
    : USE_SKILL_REQ() {
    *this = ::std::move(from);
  }

  inline USE_SKILL_REQ& operator=(const USE_SKILL_REQ& from) {
    CopyFrom(from);
    return *this;
  }
  inline USE_SKILL_REQ& operator=(USE_SKILL_REQ&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const USE_SKILL_REQ& default_instance() {
    return *internal_default_instance();
  }
  static inline const USE_SKILL_REQ* internal_default_instance() {
    return reinterpret_cast<const USE_SKILL_REQ*>(
               &_USE_SKILL_REQ_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(USE_SKILL_REQ& a, USE_SKILL_REQ& b) {
    a.Swap(&b);
  }
  inline void Swap(USE_SKILL_REQ* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(USE_SKILL_REQ* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  USE_SKILL_REQ* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<USE_SKILL_REQ>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const USE_SKILL_REQ& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const USE_SKILL_REQ& from) {
    USE_SKILL_REQ::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(USE_SKILL_REQ* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.USE_SKILL_REQ";
  }
  protected:
  explicit USE_SKILL_REQ(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDirectionFieldNumber = 2,
    kSkillIndexFieldNumber = 1,
  };
  // .Protocol.VECTOR3 direction = 2;
  bool has_direction() const;
  private:
  bool _internal_has_direction() const;
  public:
  void clear_direction();
  const ::Protocol::VECTOR3& direction() const;
  PROTOBUF_NODISCARD ::Protocol::VECTOR3* release_direction();
  ::Protocol::VECTOR3* mutable_direction();
  void set_allocated_direction(::Protocol::VECTOR3* direction);
  private:
  const ::Protocol::VECTOR3& _internal_direction() const;
  ::Protocol::VECTOR3* _internal_mutable_direction();
  public:
  void unsafe_arena_set_allocated_direction(
      ::Protocol::VECTOR3* direction);
  ::Protocol::VECTOR3* unsafe_arena_release_direction();

  // int32 skillIndex = 1;
  void clear_skillindex();
  int32_t skillindex() const;
  void set_skillindex(int32_t value);
  private:
  int32_t _internal_skillindex() const;
  void _internal_set_skillindex(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.USE_SKILL_REQ)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::Protocol::VECTOR3* direction_;
    int32_t skillindex_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_USE_5fSKILL_5fREQ_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// USE_SKILL_REQ

// int32 skillIndex = 1;
inline void USE_SKILL_REQ::clear_skillindex() {
  _impl_.skillindex_ = 0;
}
inline int32_t USE_SKILL_REQ::_internal_skillindex() const {
  return _impl_.skillindex_;
}
inline int32_t USE_SKILL_REQ::skillindex() const {
  // @@protoc_insertion_point(field_get:Protocol.USE_SKILL_REQ.skillIndex)
  return _internal_skillindex();
}
inline void USE_SKILL_REQ::_internal_set_skillindex(int32_t value) {
  
  _impl_.skillindex_ = value;
}
inline void USE_SKILL_REQ::set_skillindex(int32_t value) {
  _internal_set_skillindex(value);
  // @@protoc_insertion_point(field_set:Protocol.USE_SKILL_REQ.skillIndex)
}

// .Protocol.VECTOR3 direction = 2;
inline bool USE_SKILL_REQ::_internal_has_direction() const {
  return this != internal_default_instance() && _impl_.direction_ != nullptr;
}
inline bool USE_SKILL_REQ::has_direction() const {
  return _internal_has_direction();
}
inline const ::Protocol::VECTOR3& USE_SKILL_REQ::_internal_direction() const {
  const ::Protocol::VECTOR3* p = _impl_.direction_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::VECTOR3&>(
      ::Protocol::_VECTOR3_default_instance_);
}
inline const ::Protocol::VECTOR3& USE_SKILL_REQ::direction() const {
  // @@protoc_insertion_point(field_get:Protocol.USE_SKILL_REQ.direction)
  return _internal_direction();
}
inline void USE_SKILL_REQ::unsafe_arena_set_allocated_direction(
    ::Protocol::VECTOR3* direction) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.direction_);
  }
  _impl_.direction_ = direction;
  if (direction) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.USE_SKILL_REQ.direction)
}
inline ::Protocol::VECTOR3* USE_SKILL_REQ::release_direction() {
  
  ::Protocol::VECTOR3* temp = _impl_.direction_;
  _impl_.direction_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protocol::VECTOR3* USE_SKILL_REQ::unsafe_arena_release_direction() {
  // @@protoc_insertion_point(field_release:Protocol.USE_SKILL_REQ.direction)
  
  ::Protocol::VECTOR3* temp = _impl_.direction_;
  _impl_.direction_ = nullptr;
  return temp;
}
inline ::Protocol::VECTOR3* USE_SKILL_REQ::_internal_mutable_direction() {
  
  if (_impl_.direction_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::VECTOR3>(GetArenaForAllocation());
    _impl_.direction_ = p;
  }
  return _impl_.direction_;
}
inline ::Protocol::VECTOR3* USE_SKILL_REQ::mutable_direction() {
  ::Protocol::VECTOR3* _msg = _internal_mutable_direction();
  // @@protoc_insertion_point(field_mutable:Protocol.USE_SKILL_REQ.direction)
  return _msg;
}
inline void USE_SKILL_REQ::set_allocated_direction(::Protocol::VECTOR3* direction) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.direction_);
  }
  if (direction) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(direction));
    if (message_arena != submessage_arena) {
      direction = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, direction, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.direction_ = direction;
  // @@protoc_insertion_point(field_set_allocated:Protocol.USE_SKILL_REQ.direction)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_USE_5fSKILL_5fREQ_2eproto
